# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
          registry-url: https://npm.pkg.github.com/
      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # install dependencies
      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # run test cases
      - name: Run unit test cases
        run: yarn test

      # build the react app
      - name: Build
        run: yarn build

      # deploy the react app to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
          github_token: ${{ secrets.NPM_TOKEN }}
          publish_dir: ./build # directory to deploy

